kind: Job
apiVersion: v1
metadata:
  name: test-job
spec:
  parallelism: 2
  completions: 5
  selector:
    name: test-job
  template:
    metadata:
      labels:
        name: test-job
    spec:
      restartPolicy: Never
      containers:
      - name: basic-pod
        image: "centos:centos7"
        command: ['false']
